-- MySQL Script generated by MySQL Workbench
-- Mon Mar 21 01:42:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_myanimelist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_myanimelist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_myanimelist` DEFAULT CHARACTER SET utf8 ;
USE `db_myanimelist` ;

-- -----------------------------------------------------
-- Table `db_myanimelist`.`anime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`anime` (
  `id` INT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `english_title` VARCHAR(200) NULL,
  `type` VARCHAR(45) NULL,
  `source` VARCHAR(45) NULL,
  `start_air` DATE NULL,
  `end_air` DATE NULL,
  `season_premier` VARCHAR(45) NULL,
  `theme` VARCHAR(45) NULL,
  `rating` VARCHAR(100) NULL,
  `img_url` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`studio` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `rank` INT NULL,
  `favorites` INT NULL,
  `img_url` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`studio_anime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`studio_anime` (
  `match_id` INT NOT NULL AUTO_INCREMENT,
  `studio_id` INT NOT NULL,
  `anime_id` INT NOT NULL,
  PRIMARY KEY (`match_id`),
  INDEX `fk_studio_anime_studio1_idx` (`studio_id` ASC) VISIBLE,
  INDEX `fk_studio_anime_anime1_idx` (`anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_studio_anime_studio1`
    FOREIGN KEY (`studio_id`)
    REFERENCES `db_myanimelist`.`studio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studio_anime_anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `db_myanimelist`.`anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`genre` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`anime_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`anime_genre` (
  `match_id` INT NOT NULL AUTO_INCREMENT,
  `anime_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`match_id`),
  INDEX `fk_anime_genre_anime1_idx` (`anime_id` ASC) VISIBLE,
  INDEX `fk_anime_genre_genre1_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_anime_genre_anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `db_myanimelist`.`anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anime_genre_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `db_myanimelist`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`anime_watch_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`anime_watch_stats` (
  `anime_id` INT NOT NULL,
  `watching` INT NULL,
  `completed` INT NULL,
  `on_hold` INT NULL,
  `dropped` INT NULL,
  `plan_to_watch` INT NULL,
  `total` INT NULL,
  INDEX `fk_anime_watch_stats_animes1_idx` (`anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_anime_watch_stats_animes1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `db_myanimelist`.`anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`anime_general_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`anime_general_stats` (
  `anime_id` INT NOT NULL,
  `score` FLOAT NULL,
  `rating_count` INT NULL,
  `ranked` INT NULL,
  `popularity` INT NULL,
  `members` INT NULL,
  `favorites` INT NULL,
  INDEX `fk_anime_general_stats_animes1_idx` (`anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_anime_general_stats_animes1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `db_myanimelist`.`anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`anime_score_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`anime_score_stats` (
  `anime_id` INT NOT NULL,
  `10` INT NULL,
  `9` INT NULL,
  `8` INT NULL,
  `7` INT NULL,
  `6` INT NULL,
  `5` INT NULL,
  `4` INT NULL,
  `3` INT NULL,
  `2` INT NULL,
  `1` INT NULL,
  INDEX `fk_anime_score_stats_animes1_idx` (`anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_anime_score_stats_animes1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `db_myanimelist`.`anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`people` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `birthday` VARCHAR(50) NULL,
  `favorites` INT NULL,
  `img_url` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`staff` (
  `match_id` INT NOT NULL AUTO_INCREMENT,
  `people_id` INT NOT NULL,
  `anime_id` INT NOT NULL,
  `role` VARCHAR(500) NULL,
  PRIMARY KEY (`match_id`),
  INDEX `fk_staff_people1_idx` (`people_id` ASC) VISIBLE,
  INDEX `fk_staff_anime1_idx` (`anime_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `db_myanimelist`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `db_myanimelist`.`anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`character` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `favorites` INT NULL,
  `img_url` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`voice_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`voice_actor` (
  `match_id` INT NOT NULL AUTO_INCREMENT,
  `character_id` INT NOT NULL,
  `people_id` INT NOT NULL,
  PRIMARY KEY (`match_id`),
  INDEX `fk_voice_actor_character1_idx` (`character_id` ASC) VISIBLE,
  INDEX `fk_voice_actor_people1_idx` (`people_id` ASC) VISIBLE,
  CONSTRAINT `fk_voice_actor_character1`
    FOREIGN KEY (`character_id`)
    REFERENCES `db_myanimelist`.`character` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voice_actor_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `db_myanimelist`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_myanimelist`.`anime_character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_myanimelist`.`anime_character` (
  `match_id` INT NOT NULL AUTO_INCREMENT,
  `anime_id` INT NOT NULL,
  `character_id` INT NOT NULL,
  `role` VARCHAR(100) NULL,
  PRIMARY KEY (`match_id`),
  INDEX `fk_anime_character_anime1_idx` (`anime_id` ASC) VISIBLE,
  INDEX `fk_anime_character_character1_idx` (`character_id` ASC) VISIBLE,
  CONSTRAINT `fk_anime_character_anime1`
    FOREIGN KEY (`anime_id`)
    REFERENCES `db_myanimelist`.`anime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anime_character_character1`
    FOREIGN KEY (`character_id`)
    REFERENCES `db_myanimelist`.`character` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;