-- MySQL Script generated by MySQL Workbench
-- Wed Mar  9 22:26:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myanimelist_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myanimelist_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myanimelist_db` DEFAULT CHARACTER SET utf8 ;
USE `myanimelist_db` ;

-- -----------------------------------------------------
-- Table `myanimelist_db`.`anime_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myanimelist_db`.`anime_info` (
  `id` INT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `img_url` VARCHAR(500) NULL,
  `started_airing` DATE NULL,
  `finished_airing` DATE NULL,
  `season_premire` VARCHAR(45) NULL,
  `source` VARCHAR(45) NULL,
  `english_title` VARCHAR(200) NULL,
  `themes` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `myanimelist_db`.`anime_general_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myanimelist_db`.`anime_general_stats` (
  `score` FLOAT NULL,
  `rating_count` INT NULL,
  `ranked` INT NULL,
  `popularity` INT NULL,
  `members` INT NULL,
  `favorites` INT NULL,
  `anime_info_id` INT NOT NULL,
  INDEX `fk_anime_general_stats_anime_info1_idx` (`anime_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_anime_general_stats_anime_info1`
    FOREIGN KEY (`anime_info_id`)
    REFERENCES `myanimelist_db`.`anime_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `myanimelist_db`.`anime_watch_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myanimelist_db`.`anime_watch_stats` (
  `watching` INT NULL,
  `completed` INT NULL,
  `on-hold` INT NULL,
  `dropped` INT NULL,
  `plan_to_watch` INT NULL,
  `total` INT NULL,
  `anime_info_id` INT NOT NULL,
  INDEX `fk_anime_watch_stats_anime_info1_idx` (`anime_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_anime_watch_stats_anime_info1`
    FOREIGN KEY (`anime_info_id`)
    REFERENCES `myanimelist_db`.`anime_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `myanimelist_db`.`anime_score_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myanimelist_db`.`anime_score_stats` (
  `10` INT NULL,
  `9` INT NULL,
  `8` INT NULL,
  `7` INT NULL,
  `6` INT NULL,
  `5` INT NULL,
  `4` INT NULL,
  `3` INT NULL,
  `2` INT NULL,
  `1` INT NULL,
  `anime_info_id` INT NOT NULL,
  INDEX `fk_anime_score_stats_anime_info1_idx` (`anime_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_anime_score_stats_anime_info1`
    FOREIGN KEY (`anime_info_id`)
    REFERENCES `myanimelist_db`.`anime_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `myanimelist_db`.`people_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myanimelist_db`.`people_info` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `birthday` DATE NULL,
  `member_favorites` INT NULL,
  `img_url` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myanimelist_db`.`charecter_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myanimelist_db`.`charecter_info` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL,
  `favorites` INT NULL,
  `img_url` VARCHAR(500) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `myanimelist_db`.`charecter_voice_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myanimelist_db`.`charecter_voice_actor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `people_info_id` INT NOT NULL,
  `charecter_info_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_charecter_voice_actor_people_info1_idx` (`people_info_id` ASC) VISIBLE,
  INDEX `fk_charecter_voice_actor_charecter_info1_idx` (`charecter_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_charecter_voice_actor_people_info1`
    FOREIGN KEY (`people_info_id`)
    REFERENCES `myanimelist_db`.`people_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_charecter_voice_actor_charecter_info1`
    FOREIGN KEY (`charecter_info_id`)
    REFERENCES `myanimelist_db`.`charecter_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `myanimelist_db`.`anime_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myanimelist_db`.`anime_staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `staff_role` VARCHAR(45) NOT NULL,
  `anime_info_id` INT NOT NULL,
  `people_info_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_anime_staff_anime_info1_idx` (`anime_info_id` ASC) VISIBLE,
  INDEX `fk_anime_staff_people_info1_idx` (`people_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_anime_staff_anime_info1`
    FOREIGN KEY (`anime_info_id`)
    REFERENCES `myanimelist_db`.`anime_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anime_staff_people_info1`
    FOREIGN KEY (`people_info_id`)
    REFERENCES `myanimelist_db`.`people_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `myanimelist_db`.`character_anime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myanimelist_db`.`character_anime` (
  `id` INT NOT NULL,
  `charecter_info_id` INT NOT NULL,
  `anime_info_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_character_anime_charecter_info1_idx` (`charecter_info_id` ASC) VISIBLE,
  INDEX `fk_character_anime_anime_info1_idx` (`anime_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_character_anime_charecter_info1`
    FOREIGN KEY (`charecter_info_id`)
    REFERENCES `myanimelist_db`.`charecter_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_anime_anime_info1`
    FOREIGN KEY (`anime_info_id`)
    REFERENCES `myanimelist_db`.`anime_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myanimelist_db`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myanimelist_db`.`genres` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myanimelist_db`.`anime_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myanimelist_db`.`anime_genre` (
  `id` INT NOT NULL,
  `genres_id` INT NOT NULL,
  `anime_info_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_anime_genre_genres1_idx` (`genres_id` ASC) VISIBLE,
  INDEX `fk_anime_genre_anime_info1_idx` (`anime_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_anime_genre_genres1`
    FOREIGN KEY (`genres_id`)
    REFERENCES `myanimelist_db`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anime_genre_anime_info1`
    FOREIGN KEY (`anime_info_id`)
    REFERENCES `myanimelist_db`.`anime_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
